# Generated by Django 5.1.8 on 2025-04-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=15)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('air_quality', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
