# Generated by Django 5.1.8 on 2025-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='air_quality',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
