# Generated by Django 5.1.8 on 2025-04-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_alter_sensor_air_quality_alter_sensor_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
